In [59]:
from numpy import array
import tensorflow as tf
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
from keras.optimizers import SGD, Adam
import numpy as np
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = tf.convert_to_tensor(np.array([1,1,1,1,1,0,0,0,0,0]))
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
padded_docs = tf.convert_to_tensor(padded_docs)
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model

model.compile(optimizer=Adam(), loss='mse', metrics=['accuracy'])
# summarize the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=1)

print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=1, verbose=1, steps_per_epoch = 100)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=1)
print('Accuracy: %f' % (accuracy*100))
model.weights


[[33, 25], [1, 44], [29, 18], [23, 44], [45], [44], [22, 18], [12, 1], [22, 44], [23, 48, 25, 9]]
tf.Tensor(
[[33 25  0  0]
 [ 1 44  0  0]
 [29 18  0  0]
 [23 44  0  0]
 [45  0  0  0]
 [44  0  0  0]
 [22 18  0  0]
 [12  1  0  0]
 [22 44  0  0]
 [23 48 25  9]], shape=(10, 4), dtype=int32)
1/1 [==============================] - 0s 1ms/step - loss: 0.2469 - accuracy: 0.7000
Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_17 (Embedding)     (None, 4, 8)              400       
_________________________________________________________________
flatten_17 (Flatten)         (None, 32)                0         
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
1/1 [=

[<tf.Variable 'embedding_17/embeddings:0' shape=(50, 8) dtype=float32, numpy=
 array([[        nan,         nan,         nan,         nan,         nan,
                 nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,         nan,
                 nan,         nan,         nan],
        [-0.00975901,  0.03659991,  0.00138086, -0.01770953, -0.039822  ,
          0.04544142,  0.01020611, -0.01391403],
        [ 0.01775413,  0.01328962,  0.0058982 ,  0.03776171,  0.00299578,
          0.01581695,  0.00724781, -0.00015415],
        [-0.01844171, -0.03373764, -0.00300369, -0.03986211, -0.03833828,
         -0.04944567,  0.01866418,  0.02923513],
        [ 0.04291641,  0.04631516,  0.03798593,  0.0172174 , -0.02843343,
         -0.00742146,  0.03445714,  0.00929978],
        [-0.04071433,  0.03870375, -0.02513969,  0.02151484,  0.03394372,
         -0.04691219, -0.01671691, -0.04387248],
        [-0.01156149,  0.0364265 , -0.00733619, -0.04134567, 

In [64]:
model.device

AttributeError: 'Sequential' object has no attribute 'device'

In [62]:
import keras
keras.__version__

'2.4.3'

In [63]:
tf.__version__

'2.3.0'

In [46]:
model.predict(padded_docs)

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=float32)

In [9]:
padded_docs

array([[33, 25,  0,  0],
       [ 1, 44,  0,  0],
       [29, 18,  0,  0],
       [23, 44,  0,  0],
       [45,  0,  0,  0],
       [44,  0,  0,  0],
       [22, 18,  0,  0],
       [12,  1,  0,  0],
       [22, 44,  0,  0],
       [23, 48, 25,  9]])

[<tf.Variable 'embedding_7/embeddings:0' shape=(50, 8) dtype=float32, numpy=
 array([[        nan,         nan,         nan,         nan,         nan,
                 nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,         nan,
                 nan,         nan,         nan],
        [-0.01492083, -0.02976065, -0.01549443,  0.02936831, -0.00519624,
          0.02345714, -0.00900381,  0.02160739],
        [-0.01563947,  0.03499044,  0.04195911, -0.00820928,  0.01859761,
          0.03502626, -0.0036392 , -0.04014714],
        [ 0.0149253 ,  0.04101967, -0.03607244,  0.04328681, -0.01374529,
          0.03189918, -0.01114007,  0.03640575],
        [-0.00171951,  0.02650141,  0.03808595, -0.00699276,  0.02841487,
          0.0461097 ,  0.01732432, -0.03013566],
        [ 0.01084407,  0.00994591,  0.02445711,  0.0182477 , -0.03799838,
         -0.00964101, -0.00401131, -0.00267639],
        [ 0.01701654,  0.02725198, -0.00345892, -0.02969965,  

In [10]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.preprocessing import text
tokenizer = text.Tokenizer(num_words=50)

docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']


tokenizer.fit_on_texts(docs)
def prep_text(texts, tokenizer, max_sequence_length):
    # Turns text into into padded sequences.
    text_sequences = tokenizer.texts_to_sequences(texts)
    return sequence.pad_sequences(text_sequences, maxlen=max_sequence_length)

sequences = 

In [11]:
tokenizer